version: '3'
services:
  backend:
    container_name: back-server
    build:
      context: ./backend/koala_back
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - TZ=Asia/Seoul
    env_file:
      - /home/ubuntu/.env
    networks:
      - koala

  frontend:
    container_name: front-client
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      - koala

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /home/ubuntu/nginx.conf:/etc/nginx/nginx.conf
      - /home/ubuntu/certbot/conf:/etc/letsencrypt
      - /home/ubuntu/certbot/www:/var/www/certbot
    networks:
      - koala

  certbot:
    image: certbot/certbot
    volumes:
      - /home/ubuntu/certbot/conf:/etc/letsencrypt
      - /home/ubuntu/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

networks:
  koala:


